import React from 'react';

const ReportView = ({ data, onBack }) => {
  if (!data) return null;

  const { url, summary, answer, nlp_data, timestamp = new Date().toLocaleDateString() } = data;

  return (
    <div className="report-container" style={{ 
      background: 'white', 
      color: '#1a1a1a', 
      minHeight: '100vh', 
      padding: '4rem 2rem',
      fontFamily: '"Inter", sans-serif'
    }}>
      <div style={{ maxWidth: '800px', margin: '0 auto' }}>
        
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '2px solid #06b6d4', paddingBottom: '1.5rem', marginBottom: '3rem' }}>
          <div>
            <h1 style={{ fontSize: '2rem', fontWeight: 800, color: '#06b6d4', margin: 0 }}>LINKLYT AI</h1>
            <p style={{ fontSize: '0.875rem', color: '#666', marginTop: '0.25rem' }}>Intelligence & Research Report</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <p style={{ fontSize: '0.875rem', fontWeight: 600, margin: 0 }}>Date: {timestamp}</p>
            <p style={{ fontSize: '0.75rem', color: '#888', margin: 0 }}>ID: {Math.random().toString(36).substring(7).toUpperCase()}</p>
          </div>
        </div>

        {/* Source Info */}
        <div style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1rem', marginBottom: '0.5rem', color: '#444' }}>Source Information</h2>
          <div style={{ padding: '1rem', background: '#f8fafc', borderRadius: '0.5rem', border: '1px solid #e2e8f0' }}>
            <p style={{ margin: 0, fontSize: '0.9rem', wordBreak: 'break-all' }}><strong>URL:</strong> <span style={{ color: '#06b6d4' }}>{url}</span></p>
          </div>
        </div>

        {/* NLP Insights */}
        {nlp_data && (
          <div style={{ marginBottom: '2.5rem' }}>
            <h2 style={{ fontSize: '1rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1rem', marginBottom: '0.5rem', color: '#444' }}>Semantic Intelligence</h2>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '1rem' }}>
              <span style={{ padding: '0.25rem 0.75rem', background: '#06b6d4', color: 'white', borderRadius: '1rem', fontSize: '0.75rem', fontWeight: 700 }}>
                SENTIMENT: {nlp_data.sentiment?.toUpperCase()}
              </span>
              {nlp_data.entities?.map((ent, i) => (
                <span key={i} style={{ padding: '0.25rem 0.75rem', background: '#e2e8f0', borderRadius: '1rem', fontSize: '0.75rem', fontWeight: 600 }}>
                  {ent}
                </span>
              ))}
            </div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
              {nlp_data.keywords?.map((kw, i) => (
                <span key={i} style={{ fontSize: '0.8rem', color: '#64748b' }}>#{kw}</span>
              ))}
            </div>
          </div>
        )}

        {/* Executive Summary */}
        <div style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1rem', marginBottom: '0.5rem', color: '#444' }}>Executive Summary</h2>
          <div style={{ lineHeight: '1.6', fontSize: '1rem', color: '#334155', whiteSpace: 'pre-line' }}>
            {summary}
          </div>
        </div>

        {/* AI Analysis */}
        <div style={{ marginBottom: '4rem' }}>
          <h2 style={{ fontSize: '1rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1rem', marginBottom: '0.5rem', color: '#444' }}>Detailed Analysis</h2>
          <div style={{ padding: '1.5rem', background: '#f1f5f9', borderRadius: '1rem', borderLeft: '4px solid #06b6d4', lineHeight: '1.6', color: '#1e293b' }}>
            {answer}
          </div>
        </div>

        {/* Footer */}
        <div style={{ borderTop: '1px solid #e2e8f0', paddingTop: '1.5rem', textAlign: 'center', color: '#94a3b8', fontSize: '0.75rem' }}>
          <p>Generated by Linklyt AI Research Engine. Confidential Intelligence Report.</p>
          <div className="no-print" style={{ marginTop: '2rem', display: 'flex', justifyContent: 'center', gap: '1rem' }}>
            <button onClick={() => window.print()} style={{ padding: '0.75rem 2rem', background: '#06b6d4', color: 'white', border: 'none', borderRadius: '0.5rem', fontWeight: 700, cursor: 'pointer' }}>Download PDF</button>
            <button onClick={onBack} style={{ padding: '0.75rem 2rem', background: 'white', border: '1px solid #cbd5e1', borderRadius: '0.5rem', fontWeight: 700, cursor: 'pointer' }}>Back to Dashboard</button>
          </div>
        </div>

      </div>

      <style dangerouslySetInnerHTML={{ __html: `
        @media print {
          .no-print { display: none !important; }
          body { background: white !important; }
          .report-container { padding: 0 !important; }
        }
      `}} />
    </div>
  );
};

export default ReportView;
